# Generated by Django 5.0.2 on 2024-02-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='images',
            field=models.ImageField(upload_to='movie/images/'),
        ),
    ]
